name: Build and Deploy
on:
  push:
    branches:
      - master
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.9
    - run: julia --project=slideshow -e 'import Pkg; Pkg.instantiate()'
    - run: julia --project=slideshow slideshow/make.jl
    - run: julia --project=page page/make.jl
    - run: cp -r slideshow/ page/__site/slideshow
    - run: touch page/__site/.nojekyll
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        BRANCH: gh-pages
        FOLDER: page/__site
